<a href="https://colab.research.google.com/github/jpcaico/PyTorch-Fun/blob/main/PyTorch_TensorMathOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensor Math Operations
- Add, Subtract, Multiply, Divide, Remainders, Exponents
- Shorthand and longhand
- Reassignment

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [5]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [6]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [7]:
tensor_a * 2

tensor([2, 4, 6, 8])

In [8]:
## Addition longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [9]:
torch.subtract(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

In [10]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [11]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [12]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [15]:
## Reassignment

tensor_a.add_(tensor_b) # the underscore is similar to a inplace

tensor([11, 14, 17, 20])

In [14]:
tensor_a

tensor([ 6,  8, 10, 12])