<a href="https://colab.research.google.com/github/jpcaico/PyTorch-Fun/blob/main/PyTorch_TensorOperations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Tensors

- A torch.Tensor is a multi-dimensional matrix containing elements of a single data type
- Similar to a Numpy Array, but full of things that make them work better on GPU's (vs regular CPU's)
- default data type of float32
- More suitable for deep learning than a numpy array

In [2]:
import torch
import numpy as np

In [4]:
## Lists

my_list = [[1,2,3,4,5,6], [7,8,9,10]]
my_list

[[1, 2, 3, 4, 5, 6], [7, 8, 9, 10]]

In [7]:
## Numpy Arrays
np1 = np.random.rand(3,4)
print(np1.dtype)
print(np1)

float64
[[0.08486456 0.65677163 0.60391308 0.44324062]
 [0.98989011 0.32058945 0.07271034 0.91065576]
 [0.17676517 0.42382616 0.62465362 0.78464601]]


In [8]:
## Tensors
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[ 0.3948,  0.4710,  0.7083,  1.4457],
        [-0.6407,  1.6590,  0.6057, -1.6188],
        [ 0.2121, -0.5243, -0.3368, -0.9509]])

In [10]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [11]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.0849, 0.6568, 0.6039, 0.4432],
        [0.9899, 0.3206, 0.0727, 0.9107],
        [0.1768, 0.4238, 0.6247, 0.7846]], dtype=torch.float64)

In [12]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
# Reshape and View
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
# Reshape if we don't know the number of items using -1

my_torch2 = torch.arange(16)
my_torch2

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [18]:
my_torch2 = my_torch2.reshape(2, -1)
my_torch2

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7],
        [ 8,  9, 10, 11, 12, 13, 14, 15]])

In [20]:
my_torch2.reshape(-1, 4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])

In [21]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [24]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [26]:
my_torch5[1] = 4141
my_torch5

tensor([   0, 4141,    2,    3,    4,    5,    6,    7,    8,    9])

In [27]:
my_torch6

tensor([[   0, 4141,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [28]:
# Slices

my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
my_torch7[7]

tensor(7)

In [31]:
# grab a slice
my_torch8 = my_torch7.reshape(5,2)

In [32]:
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [35]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [36]:
# return column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])